/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "ConectaFapes Docs",
  "favicon": "img/favicon.ico",
  "url": "https://ledsifes.gitlab.io",
  "baseUrl": "/conectafapes-project/",
  "organizationName": "leds-conectafapes",
  "projectName": "Conecta Fapes",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "plugins": [
    "C:\\leds-org\\conectafapes-project\\documentation\\node_modules\\docusaurus-lunr-search\\src\\index.js"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "breadcrumbs": true,
          "showLastUpdateTime": true,
          "includeCurrentVersion": true,
          "docsRootComponent": "@theme/DocsRoot",
          "docVersionRootComponent": "@theme/DocVersionRoot",
          "docRootComponent": "@theme/DocRoot",
          "docItemComponent": "@theme/DocItem",
          "routeBasePath": "/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "footer": {
      "style": "light",
      "copyright": "Copyright © 2025. Desenvolvido por <a href=\"https://www.instagram.com/ledsifes/\">LEDS</a>, utilizando o Docusaurus.",
      "links": []
    },
    "mermaid": {
      "options": {
        "fontSize": 18
      },
      "theme": {
        "dark": "dark",
        "light": "default"
      }
    },
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": false
      },
      "versionPersistence": "localStorage"
    },
    "image": "img/leds-social-card.jpg",
    "navbar": {
      "title": "Home",
      "logo": {
        "src": "img/fapes1.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "gestao",
          "position": "left",
          "label": "Gestão"
        },
        {
          "type": "docSidebar",
          "sidebarId": "modulos",
          "label": "Módulos",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "sidebarId": "desenvolvimento",
          "position": "left",
          "label": "Processos de Desenvolvimento"
        },
        {
          "type": "docSidebar",
          "sidebarId": "referencias",
          "position": "left",
          "label": "Referências"
        },
        {
          "type": "dropdown",
          "label": "Software Design Documentation",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "label": "Conecta Fapes",
              "docId": "sdd_conecta_admin/introducao"
            }
          ]
        },
        {
          "href": "https://gitlab.com/ledsifes",
          "label": "Github",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false
};
