image: node:21

default:
  before_script:
    - cd documentation

cache:
  paths:
    - documentation/node_modules/
    - documentation/public/
    - documentation/.cache/

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build:gitlab
  artifacts:
    paths:
      - documentation/public
  only:
    - main
