image: node:21

cache:
  paths:
    - documentation/node_modules/
    - documentation/public/
    - documentation/.cache/

pages:
  stage: deploy
  script:
    - cd documentation
    - yarn install
    - yarn build:gitlab
  artifacts:
    paths:
      - public
  only:
    - main
