image: node:21

cache:
  paths:
    - documentation/node_modules/
    - documentation/.cache/

pages:
  stage: deploy
  script:
    - cd documentation
    - yarn install
    - yarn build:gitlab
    - cd ..
    - mkdir public
    - cp -r documentation/public/* public/
  artifacts:
    paths:
      - public
    when: always
  only:
    - main
