@startuml
package "Gerenciar Editais" {
}

package "Modalidades de Bolsas" {
}

package "Importação de Editais"{

}

package "Pagamento de Bolsistas"{

}

package "Visualização de Pagamento"{

}

"Gerenciar Editais" --> "Modalidades de Bolsas"
"Importação de Editais" --> "Gerenciar Editais"
"Importação de Editais" --> "Modalidades de Bolsas"
"Pagamento de Bolsistas" --> "Gerenciar Editais"
"Pagamento de Bolsistas" --> "Modalidades de Bolsas"
"Visualização de Pagamento" --> "Pagamento de Bolsistas"
"Visualização de Pagamento" --> "Gerenciar Editais"
@enduml