import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  gestao: [{type: 'autogenerated', dirName: 'gestao'}],

  // processonegocio: [{type: 'autogenerated', dirName: 'processonegocio'}],

  desenvolvimento: [{type: 'autogenerated', dirName: 'desenvolvimento'}],

  bi: [{type: 'autogenerated', dirName: 'bi'}],

  qa: [{type: 'autogenerated', dirName: 'qualidade'}],

  devops: [{type: 'autogenerated', dirName: 'devops'}],

  referencias: [{type: 'autogenerated', dirName: 'referencias'}],

  colatina: [{type: 'autogenerated', dirName: 'colatina'}],
  
  sdd_conecta_admin: [{type: 'autogenerated', dirName: 'sdd_conecta_admin'}],
};

export default sidebars;