import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  gestao: [{type: 'autogenerated', dirName: 'gestao'}],

  modulos: [{type: 'autogenerated', dirName: 'modulos'}],

  desenvolvimento: [{type: 'autogenerated', dirName: 'desenvolvimento'}],

  referencias: [{type: 'autogenerated', dirName: 'referencias'}],
  
  sdd_conecta_admin: [{type: 'autogenerated', dirName: 'sdd_conecta_admin'}],
};

export default sidebars;